name: RASCL
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - biopython=1.77
  - hyphy=2.5.31 
  - raxml-ng=1.0.2 
  - snakemake=5.3
  - stephenshank::tn93=1.0.7
  - python-bioext=0.19.7
  - python=3.6
